### ISSUE TITLE
Suggestion: add the dogsheep tag to the repo

### ISSUE THREAD

**Issue by simonw** [rixx/goodreads-to-sqlite#2]
Then it will show up on https://github.com/topics/dogsheep

**Comment by rixx** [comment]
Sure – I also put "dogsheep" down as one of the ``keywords`` in the ``setup.py``, so that this package will show up in a PyPI search for "dogsheep". Your repos apparently show up in any case, because the repo URL is searched, but maybe you could add the keyword to your repos, too, so that others will do the same when looking at them?
